### ISSUE TITLE
Real-time member counter

### ISSUE THREAD

**Issue by ghost** [SwitchbladeBot/bladey-web#15]
_A member counter on the Discord site that shows how many members it has at the exact moment and over time if you join a member or exit or leave it will update simultaneously on the site as an sub-counter but for number of members in the Discord._

Example
![2018-07-16_23-05-02](https://user-images.githubusercontent.com/39033999/42792897-d7259e6c-894d-11e8-9de0-b288c5b22c3a.gif)

**Comment by davipatury** [comment]
https://github.com/xlsdg/vue-odometer

**Comment by Doges** [comment]
We can't do this anymore as we don't have the intent needed.
