### ISSUE TITLE
Pages missing user images

### ISSUE THREAD

**Issue by dsgpaiva** [SwitchbladeBot/bladey-web#16]
https://switchblade.xyz/contributors n' login avatars
![image](https://user-images.githubusercontent.com/32089154/42938820-7a6c0eb8-8b4b-11e8-9607-e156e1925ccf.png)
![image](https://user-images.githubusercontent.com/32089154/42938830-82e8b6b8-8b4b-11e8-8f49-2708d5161f80.png)

**Comment by davipatury** [comment]
Could not reproduce.

**Comment by dsgpaiva** [comment]
Shift + F5

**Comment by dsgpaiva** [comment]
(this will be fixed on https://github.com/SwitchbladeBot/bladey-api/pull/2)

**Comment by davipatury** [comment]
This is issue is related to webp being unsupported in some browsers. cb5204c1e552ba29fb7d6258040e49018a2018db fixes it.
