### ISSUE TITLE
Command Rules: Removing a candidate from the blacklist section doesn't make the Save button light up

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/bladey-web#65]
![image](https://user-images.githubusercontent.com/25179120/67037489-00588b00-f0f4-11e9-8f61-2fb1d8149f09.png)
![image](https://user-images.githubusercontent.com/25179120/67037501-051d3f00-f0f4-11e9-9fbd-328de4715b85.png)

The Save button stays disabled even though I made changes to the rules

**Comment by davipatury** [comment]
Fixed in 6f98ca7
