### ISSUE TITLE
Can't start, stuck at 69%(vue-slider-component.theme.scss)

### ISSUE THREAD

**Issue by ghost** [SwitchbladeBot/bladey-web#88]
it has been like this for the past 10 minutes now:
![image](https://user-images.githubusercontent.com/88494432/148790643-4b1df733-02e4-4328-aabc-d77dfb979c0f.png)

what should i do? i updated all the packages that wasnt deprecated

**Comment by Doges** [comment]
Hi! We only provide support for our official instance (https://switchblade.xyz), the code is outdated and we don't have any plans to update bladey-web for now, instead we are planning to make a brand new website.

Thanks!
